### ISSUE TITLE
dev-libs/libdigidocpp-3.13.1 fails to compile

### ISSUE THREAD

**Issue by jaakristioja** [open-eid/gentoo#16]
build.log:
```
/var/tmp/portage/dev-libs/libdigidocpp-3.13.1/work/libdigidocpp-3.13.1/src/xml/ObjectType.h:31:20: error: 'QualifyingPropertiesType' in namespace 'digidoc::xades' does not name a type
     typedef xades::QualifyingPropertiesType QualifyingPropertiesType;
                    ^~~~~~~~~~~~~~~~~~~~~~~~
 ```

**Comment by jaakristioja** [comment]
Full [build.log](https://github.com/open-eid/gentoo/files/1631250/build.log)

**Comment by metsma** [comment]
gentoo shiped xsd generates invalid c++ files
```
namespace digidoc
{
  namespace xades
  {
    class AnyTypeBase;
    class cxx_uAnyType;
    class cxx_uObjectIdentifierType;
...
```
adds "cxx_u" to classname front
try to use prebuilt xsd binaries 
https://www.codesynthesis.com/download/xsd/

**Comment by martinpaljak** [comment]
Is there a reason why the generated files can't be included in git?

**Comment by metsma** [comment]
Really don't want include total 2.4M source blobs in git

**Comment by jaakristioja** [comment]
If this is a bug with another Gentoo package, a bug should be filed to [bugs.gentoo.org](https://bugs.gentoo.org/). I'd do so myself, but unfortunately I know almost next to nothing about libdigidocpp internals or xsd, so it would probably not be worth the effort.

Some quick grepping of the patches that the Gentoo ebuild applies on top of xsd as well as its source code for "cxx_u" revealed nothing. I have no clue where that could come from.

**Comment by urmet** [comment]
First, sorry for not replying earlier.

The root of the problem actually resides in libcutl, which xsd depends on, which was incorrectly fixed after boost dropped their regex wrappers. I have a patched version for the overlay on my machine but haven't pushed it yet because of some other compile failures I haven't able to track down yet. I have pushed my current work up to the libcutl patch now. Please test with dev-cpp/libcutl/libcutl-1.10.0-r1 built from this overlay. Additional details with links are in commit message of 50e0c897161f8f470effd2abbd475ace68f99c76

**Comment by jaakristioja** [comment]
libdigidocpp-3.13.1 now seems to build fine with the latest state of this overlay.
